version: '3'
services:
  mdbservice:
    image: mariadb:10.2
    environment:
      TZ: 'Asia/Singapore'
      MYSQL_ROOT_PASSWORD: kakokaba
    ports:
      - 3390:3306
    volumes:
      - './mariadb/init:/docker-entrypoint-initdb.d'
    networks:
      - mdbnetwork

networks:
  mdbnetwork:
