# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/lunar64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  config.vm.define "app1" do |app1|
    app1.vm.hostname = "hello.app1.dev"
    app1.vm.network :private_network, ip: "192.168.10.1"
 end

  config.vm.define "app2" do |app2|
    app2.vm.hostname = "hello.app2.dev"
    app2.vm.network :private_network, ip: "192.168.10.2"
  end

  config.vm.define "app3" do |app3|
    app3.vm.hostname = "hello.app3.dev"
    app3.vm.network :private_network, ip: "192.168.10.3"
  end

end